[processor.make]
exclude_paths = ["Makefile"]

[processor.pyrefly]
enabled = false

[processor.markdownlint]
enabled = false

[processor.ascii_check]
enabled = false

[processor.mdl]
enabled = false

[processor.a2x]
enabled = false

[processor.rumdl]
enabled = false
